/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>

// #include <iostream>
// #include <iomanip>
// #include <utility>

// #include <cstdint>
// #include <iomanip>
// #include <iostream>
// #include <type_traits>
// #include <utility>

// #include "app.h"
#include "memory.hpp"
#include "6502.hpp"

// std::string Greeter::greeting()
// {
//     return std::string("Hello, World!");
// }

// Forward declarations
void loadProgram(cpu::Memory memory);

// ===== Entry Pointt =====
int main()
{
    cpu::Memory memory;
    cpu::Processor processor(memory);

    loadProgram(memory);

    // std::cout << memory.name() << std::endl;
    std::cout << processor.currentMemory().name() << std::endl;
    processor.showRegisters();

    processor.execute(1);

    processor.showRegisters();

    return 0;
}

void loadProgram(cpu::Memory memory)
{
    // model.registers.PC = std::to_underlying(HardwareVector::RESET);
    // cpu::Address = std::to_underlying(cpu::HardwareVector::RESET);
    int address = std::to_underlying(cpu::HardwareVector::RESET);

    memory.write(0x0000, 0xA9); // LDA #00 // starting instruction after reset
    memory.write(0x0001, 0x00); //
    memory.write(0x0002, 0x09); // ORA #A5
    memory.write(0x0003, 0xA5); //

    // Reset vector points to start of memory
    memory.write(0xFFFC, 0x00); // cpu::HardwareVector::RESET
    memory.write(0xFFFB, 0x00); //      MSB
}
