/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>

// #include <iostream>
// #include <iomanip>
// #include <utility>

// #include <cstdint>
// #include <iomanip>
// #include <iostream>
// #include <type_traits>
// #include <utility>

// #include "app.h"
#include "memory.hpp"
#include "6502.hpp"
#include "TutorialConfig.h"

// Forward declarations
void loadProgram(memory::Memory memory);

// ===== Entry Pointt =====
int main(int argc, char **argv)
{
    if (argc < 2)
    {
        // report version
        std::cout << argv[0] << " Version " << EMU_VERSION_MAJOR << "."
                  << EMU_VERSION_MINOR << "."
                  << EMU_VERSION_PATCH << std::endl;
        std::cout << "Usage: " << argv[0] << std::endl;
        // return 1;
    }

    memory::Memory memory;
    m6502::CPU processor(memory);

    loadProgram(memory);

    // std::cout << memory.name() << std::endl;
    std::cout << processor.currentMemory().name() << std::endl;
    processor.showRegisters();

    processor.execute(1);

    processor.showRegisters();

    return 0;
}

void loadProgram(memory::Memory memory)
{
    // cpu::Address = std::to_underlying(cpu::HardwareVector::RESET);
    // int address = std::to_underlying(m6502::HardwareVector::RESET);

    memory.write(0x0000, 0x49); // LDA #00 // starting instruction after reset
    memory.write(0x0001, 0xCC); //
    memory.write(0x0002, 0x09); // ORA #A5
    memory.write(0x0003, 0xA5); //

    memory.write(0x00CC, 0x42); //
    memory.write(0xCC09, 0x62);
    memory.write(0x09CC, 0x26);

    // Reset vector points to start of memory
    memory.write(0xFFFC, 0x00); // cpu::HardwareVector::RESET
    memory.write(0xFFFB, 0x00); //      MSB
}

/*
    memory.write(0x0000, 0xA9); // LDA #00 // starting instruction after reset
    memory.write(0x0001, 0xCC); //
    memory.write(0x0002, 0x09); // ORA #A5
    memory.write(0x0003, 0xA5); //

    memory.write(0x00CC, 0x42); //

    // Reset vector points to start of memory
    memory.write(0xFFFC, 0x00); // cpu::HardwareVector::RESET
    memory.write(0xFFFB, 0x00); //      MSB
*/